- name: 作業用ディレクトリを初期化する
  become: yes
  file:
    path: '{{ work_dir }}'
    state: absent

- name: 作業用ディレクトリを作成する 
  become: yes
  file:
    path: '{{ work_dir }}'
    state: directory
    mode: 0755
